### ISSUE TITLE
Option to open configuration GUI on program start and to close program when closing GUI

### ISSUE THREAD

**Issue by bfedie518** [Macro-Deck-App/Macro-Deck#192]
**Is your feature request related to a problem? Please describe.**
When I start Macro Deck from the start menu or with a desktop shortcut, I have to then find the icon in the taskbar and right-click to open the configuration GUI.

When I close the configuration GUI, I have to find the taskbar icon and right-click to close Macro Deck.

**Describe the solution you'd like**
Add a toggle in the preferences menu to open configuration GUI upon program start and a toggle to close program upon closing GUI.

**Describe alternatives you've considered**
Just deal without these small QoL features.

**Additional context**
Other people would prefer the current behavior, so the options should be a toggle in the preferences.

**Comment by manuelmayer-dev** [comment]
You can add the `--show` start parameter to the shortcut, then it will show the gui after Macro Deck is started.
