### ISSUE TITLE
Recording Time on WebSocket Plugin

### ISSUE THREAD

**Issue by pkzaum** [Macro-Deck-App/Macro-Deck#225]
**Is your feature request related to a problem? Please describe.**
The lack of a variable of Recorded Time. Ex. Same as StreamTime [...]

**Describe the solution you'd like**
Update recording time when obs_recording value is true.

**Describe alternatives you've considered**
I have considered using the HeartBeat to get the TotalRecordTime
But since Hearbeat looks deprecated, Im kind of worried about losing this functionality.

*Functional Example using HeartBeat in the attached image.

**Additional context**
This is what I have done:

![RecordTimeFunction](https://user-images.githubusercontent.com/13563389/165895961-fe2f6366-f410-4a8a-99e7-af8c84ebfe64.png)

![MD2_OnAction](https://user-images.githubusercontent.com/13563389/165898507-bbc2b5d2-3d6f-441c-96f1-e41f453677ca.png)

**I will be using Macro Deck to reduce waste of time during my game development journey, so Im taking some time to see how I can improve it doing little adjustments until next update.

Grateful for the attention,
Jean.

**Comment by jbcarreon123** [comment]
It is much better to go to the [plugin repo](https://github.com/SuchByte/Macro-Deck-OBS-WebSocket-Plugin) and post the same issue there.

**Comment by manuelmayer-dev** [comment]
This is the wrong repository. Use the plugin's repository instead.
https://github.com/manuelmayer-dev/Macro-Deck-OBS-WebSocket-Plugin
