### ISSUE TITLE
USB/ADB: App catches up after standby

### ISSUE THREAD

**Issue by WulfmanGer** [Macro-Deck-App/Macro-Deck#230]
(grr sorry for the subject - no idea how to name it better)

I use MD on an Android tablet via USB (adb). My tablet is permanently connected - but not always actively in use and here is the problem:

1) I start the PC
2) MD is started automatically - my tablet also becomes active
3) I open the MD app @ tablet (11pm)
4) do something there - doesn't matter
5) turn off the display from the tablet (23:15= - but the app is still running in the background (MD@Win: connected) - no desire to close the app)
...
6) Some hours later (02:00): I shut down the PC.
7) next day I start PC - also end tablet screen lock and then the app rattles through - the "time" ({time}) runs: 23:15.... 23:16 ... 00:00... 01:00... 2 o'clock ... Ready ... (very quickly, of course - but I can see my entire "Windows history" (everything I opened between 11:15 pm and 2 am) via {focused_application}).

Doesn't seem normal to me. It probably only really bothers me when I'm offline for 1 week ;) *wait**wait*

**Comment by manuelmayer-dev** [comment]
Sounds like an issue of the app.
https://github.com/Macro-Deck-App/Macro-Deck-Client
