### ISSUE TITLE
bug with focus on firefox

### ISSUE THREAD

**Issue by darkgodz** [Macro-Deck-App/Macro-Deck#232]
when i use windows utlis plugin
i configure a button for start\focus for Firefox
when i click the button, the Firefox will open fine, but when i click again for focusing, it's not work, it's only work for a short time when i restart macro deck and then stop working again.

here the log file (after checking it myself, i didn't see anything that can be connected to the bug but the more eye's the better the result. )

[2022-05-26.log](https://github.com/Macro-Deck-org/Macro-Deck/files/8777910/2022-05-26.log)

**Comment by DoingFedTime** [comment]
I'm having this issue with every application. Each was set with the same flag, of start/focus and none of them actually focus.

**Comment by manuelmayer-dev** [comment]
Wrong repository

**Comment by kapitanluffy** [comment]
Experiencing the same issue have you guys found any workarounds?
