### ISSUE TITLE
OBS hotkey issue for macrodeck.

### ISSUE THREAD

**Issue by Gelealdo** [Macro-Deck-App/Macro-Deck#241]
Hello, I have a problem related to OBS studio hotkeys, I have a Dell i7 desktop, with windows 11 installed, I use the Macro Deck in OBS, and I noticed that the Macro Deck only works with the hotkeys function when the macro deck is selected, when it is behind OBS it does not work. there are some incompatibilities with OBS.

**Comment by JonathanVegaCis** [comment]
If you happen to have the OBS as an administrator, you can remove the permissions from the OBS or give the administrator permissions to the MacroDeck.
Either way should work.

> I don't speak English, I've used a translator.

**Comment by Gelealdo** [comment]
Obrigado! JonathanVegaCis, Instalei o Macro Deck ( como administrador) para
usar no OBS no Windows 11, estou tendo problema nas teclas de atalho, foi
feito a configuração dos atalho no OBS e também no Macro Deck, (
administrador) o problema é que a tecla de atalhos so funciona quando o
Macro deck ( está  selecionado) ativo ou na frente do OBS, quando o Macro
deck está em segundo plano, as teclas de atalho não funciona, já a
transição das câmeras funcionam bem, Já desativei o firewall e nada o que
pode ser ?

Em sáb., 18 de jun. de 2022 13:28, JonathanVegaCis ***@***.***>
escreveu:
