### ISSUE TITLE
start applications with arguments loaded from variables

### ISSUE THREAD

**Issue by salinashf** [Macro-Deck-App/Macro-Deck#262]
**Plugins**: *Windows Utils* 
**Request**: 
Run an application with arguments, but the arguments can be read from variables or concatenated with variables
*Example* `Run remote desktop`
variable:
- {ip remote} =192.168.0.1

Run Application 
 - C:\Windows\system32\mstsc.exe
_Arguments_ 
- /v:**{ip_remote}**:3389

**Comment by salinashf** [comment]
in addition to being able to execute command line applications with parameters from variables,

**Thank you**

**Comment by jbcarreon123** [comment]
# Wrong repository!
Go to [Windows Utils issue tracker](https://github.com/manuelmayer-dev/Macro-Deck-Windows-Utils-Plugin) and post the feature there.
