### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by I-am-Piter** [Macro-Deck-App/Macro-Deck#276]
**Describe the bug**
Hi, my issue is about freezing android app. When i open it, I can normally click and do anything, after few minutes it freezes, and I have to restart it, than it remains normal.

**To Reproduce**
1. Go to 'app'
2. Click on 'anything few times'
3 wait a moment
4. it freezes

**Expected behavior**
normal behavior

**Additional context**
This is fairly old tablet, but i think it should run normally with this app

**Comment by Xenox003** [comment]
Hi, what android version do you use?
Does the app always freeze after a designated time or only when its beeing worked with actively?
Do the buttons still visually respond after it froze or does the app freeze completely?

Are your macro deck server and app at the newest version?

Have your tried if the issues also happen with the webclient?

**Comment by I-am-Piter** [comment]
Hi, my android version is 5.0.1, app always freezes after about minute
after i open it, then I have to restart it, and it works fine. Buttons are
not responding when app is freezed, it crashes if i try to click any
button. Server is the newest version, i havent tried web client suddenly

sob., 13 sie 2022 o 00:12 Xenox003 ***@***.***> napisał(a):

**Comment by Xenox003** [comment]
I suspect its your Android version causing those problems as its already pretty old.

As a workaround you can embed the new betaclient (https://betaclient.macrodeck.org) onto your homescreen, this will work simmilar to the app but requires an internet connection.

**Comment by Xenox003** [comment]
Did the problem go away since i posted my fix?

**Comment by I-am-Piter** [comment]
I am not very interested in web app, im waiting for updates for now

wt., 13 wrz 2022, 19:58 użytkownik Xenox003 ***@***.***>
napisał:

**Comment by Xenox003** [comment]
So the issue still occurs?

**Comment by I-am-Piter** [comment]
To be fair, i dont know, i think Yes, but i dont remember, ill check and
reply

wt., 13 wrz 2022, 20:17 użytkownik Xenox003 ***@***.***>
napisał:

**Comment by I-am-Piter** [comment]
yup, after checking Im sure, problem still occurs, but not as often

wt., 13 wrz 2022 o 20:24 I_am_Piter ***@***.***> napisał(a):
