### ISSUE TITLE
Set OBS source volume/Set OBS audio source mute blank

### ISSUE THREAD

**Issue by doxzilla** [Macro-Deck-App/Macro-Deck#277]
Source dropdown for Action, OBS-WebSocket Plugin, Set OBS source volume/Set OBS audio source mute is does not contain the audio sources from OBS.

Same as reported issue #246 which was closed by the author but has no listed fix action.

**Comment by jbcarreon123** [comment]
Please go to the [plugins repository](https://github.com/SuchByte/Macro-Deck-OBS-WebSocket-Plugin/tree/016f5e087a9fdf76bd08ec1b274b6726d4c12b37) and report it there.
