### ISSUE TITLE
Port conflict with KDE connect

### ISSUE THREAD

**Issue by tumuyan** [Macro-Deck-App/Macro-Deck#282]
**Describe the bug**
port error when KDE connect runs

**To Reproduce**

1. Install kde connect
2. install macro deck
3. restart computer 
4. macro deck prompts port error, check port is used
5. exit macro deck, check port is not used 
![image](https://user-images.githubusercontent.com/3126801/185595554-d7100f3b-9a61-44bf-931b-63de2f59825c.png)
6. open macro deck to change port, still prompts port error 
7. close kde connect
8. restart macro deck, no error

**Expected behavior**

**Screenshots**

**Additional context**

**Log file**
[2022-08-19.log](https://github.com/Macro-Deck-org/Macro-Deck/files/9381110/2022-08-19.log)

**Comment by manuelmayer-dev** [comment]
The port can be changed in the Macro Deck settings.
