### ISSUE TITLE
Twitch Marker not working

### ISSUE THREAD

**Issue by J0ssL9** [Macro-Deck-App/Macro-Deck#298]
Hello i'm using Macro Deck for a few days and the main reason i wanted to use a soft like this is for the Twitch Markers
And i can't make it works

I tried the basic option with the twitch plugin adding a marker when you press the button
I also tried an automatic message "/marker" but none of them are working

Anyone have the same issue ? Is it known ? Are there people who uses it ?

**Comment by manuelmayer-dev** [comment]
Please use the plugin's repository.
https://github.com/manuelmayer-dev/Macro-Deck-Twitch-Plugin
