### ISSUE TITLE
In OBS it looks like connected but in Macro Deck app it's not connected to OBS

### ISSUE THREAD

**Issue by pintosobs** [Macro-Deck-App/Macro-Deck#354]
In OBS it looks like connected but in Macro Deck app it's not connected to OBS

![image](https://user-images.githubusercontent.com/69796025/213941632-9bd74b26-7d9e-4131-838e-98d54578d072.png)

**Comment by manuelmayer-dev** [comment]
This is the wrong repository. Use the plugin's repository instead.
https://github.com/manuelmayer-dev/Macro-Deck-OBS-WebSocket-Plugin
