### ISSUE TITLE
Source Visibility not showing the sources of a scene

### ISSUE THREAD

**Issue by ptebet** [Macro-Deck-App/Macro-Deck#371]
Even though I do have previously used the action of control source visibility for various buttons like the image below

![image](https://user-images.githubusercontent.com/64913831/223854583-45aaee43-7e5b-439e-bb0d-af577872220a.png)

Right now If I try to edit this one or crate new control source visibility action no sources is shown like bellow

![image](https://user-images.githubusercontent.com/64913831/223854788-1060652c-c86c-4631-9274-6ace631e19b5.png)

**Comment by manuelmayer-dev** [comment]
This is the wrong repository. Use the plugin's repository instead.
https://github.com/manuelmayer-dev/Macro-Deck-OBS-WebSocket-Plugin
