### ISSUE TITLE
Restoring Backup

### ISSUE THREAD

**Issue by Tii31** [Macro-Deck-App/Macro-Deck#378]
Backup file doesn't work i made a backup on windows 11 and i installed Win10 after that i put the backup file in 
C:\Users\mosta\AppData\Roaming\Macro Deck\backups
but when i try to restore it runs without restore

**Comment by Tii31** [comment]
> Backup file doesn't work i made a backup on windows 11 and i installed Win10 after that i put the backup file in C:\Users\mosta\AppData\Roaming\Macro Deck\backups but when i try to restore it runs without restore

Log
4:41:00 AM [Macro Deck] [Error] >> Backup creation failed: Could not find file 'C:\Users\mosta\AppData\Roaming\Macro Deck\devices.json'.

**Comment by ewanjc** [comment]
You can open the backup.zip and simply extract and overwrite the files.

**Comment by manuelmayer-dev** [comment]
Fixed with https://github.com/Macro-Deck-App/Macro-Deck/pull/445
