### ISSUE TITLE
Scene filters

### ISSUE THREAD

**Issue by Musodn** [Macro-Deck-App/Macro-Deck#379]
I tried to assign a filter state switch in Macro Deсk, but there are no filters in the list when selecting scene filters, although they are in the OBS. The default filters are not showing up either.

1. Launch Macro Deck
2. Clicked on "Change"
3. Clicked on "OBS-WebSocket Plugin"
4. Clicked on "Set OBS filter state"
5. Select my scene with filters

Expected that the drop-down list would have filters installed.

![image](https://user-images.githubusercontent.com/78144176/228087454-215198cf-0461-4499-a36c-dede2238a5e3.png)
![image](https://user-images.githubusercontent.com/78144176/228087497-fb0e0dc3-9c87-4e35-a462-3b855a2237b1.png)

[2023-03-28.log](https://github.com/Macro-Deck-App/Macro-Deck/files/11083678/2023-03-28.log)

**Comment by higanami** [comment]
I think it doesn't work for the reason that it switches source filters, not scene filter.

**Comment by manuelmayer-dev** [comment]
This is the wrong repository. Use the plugin's repository instead.
https://github.com/manuelmayer-dev/Macro-Deck-OBS-WebSocket-Plugin
