### ISSUE TITLE
Macro deck is not starting

### ISSUE THREAD

**Issue by prasann1621** [Macro-Deck-App/Macro-Deck#380]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Log file**
Please upload the latest log file (Help -> Export latest log)

**Comment by prasann1621** [comment]
![image](https://user-images.githubusercontent.com/73626094/229201695-90ff6a49-5c80-466b-8bee-99ab9b9c946e.png)

**Comment by SuchByte** [comment]
https://linuxhint.com/error-740-the-requested-operation-requires-elevation-windows-10-fixed/

It's a setting of your system.
