### ISSUE TITLE
macro deck stucked at installing a plugin.

### ISSUE THREAD

**Issue by wirytiox** [Macro-Deck-App/Macro-Deck#392]
Extension downloader is stucked while installing obs plugin or twitch (at least those where the ones that give that issue)

open the program, try to install spotify plugin and configure it. then try to install either of those plugin.
(not sure if changes anything but i was playing csgo and streaming on twitch)

it should download the plugin.

![image](https://user-images.githubusercontent.com/79142532/232177305-edf6a5d9-8d69-4761-bd4b-2b186890e515.png)

when this happen i tried closing the program from taskmanager and it made the program not turn on anymore. i guess something got corrupted

22:29:15 [Macro Deck] [Info] >> Successfully created C:\Users\juanj\AppData\Roaming\Macro Deck\logs
22:29:15 [Macro Deck] [Info] >> Successfully created C:\Users\juanj\AppData\Roaming\Macro Deck\credentials
22:29:15 [Macro Deck] [Info] >> Successfully created C:\Users\juanj\AppData\Roaming\Macro Deck\configs
22:29:15 [Macro Deck] [Info] >> Successfully created C:\Users\juanj\AppData\Roaming\Macro Deck\backups
22:29:15 [Macro Deck] [Info] >> Successfully created C:\Users\juanj\AppData\Roaming\Macro Deck\.temp
22:29:15 [Macro Deck] [Info] >> Loading language files...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
22:29:15 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
22:29:15 [Macro Deck] [Info] >> Config file not found. Entering initial setup wizard...
22:29:15 [Macro Deck] [Info] >> Set language to Spanish
22:29:18 [Macro Deck] [Info] >> Set language to English
22:29:22 [Macro Deck] [Info] >> Configuration saved
22:29:22 [Macro Deck] [Info] >> Configuration saved. Restarting Macro Deck...
22:29:24 [Macro Deck] [Info] >> 
==========================================
22:29:24 [Macro Deck] [Info] >> Starting Macro Deck version 2.12.0 build 221941808 with parameters: --show
22:29:24 [Macro Deck] [Info] >> Executable: C:\Program Files\Macro Deck\Macro Deck 2.exe
22:29:24 [Macro Deck] [Info] >> OS: Windows 8 build 9200 64 bit
22:29:24 [Macro Deck] [Info] >> Network interfaces: 
Ethernet - 192.168.0.101
Bluetooth Network Connection - 169.254.213.110
Loopback Pseudo-Interface 1 - 127.0.0.1
22:29:24 [Macro Deck] [Info] >> Loading language files...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
22:29:24 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
22:29:24 [Macro Deck] [Info] >> Successfully read configuration file
22:29:24 [Macro Deck] [Info] >> Set language to English
22:29:24 [Macro Deck] [Info] >> VariableManager: Initialize variables database...
22:29:24 [Macro Deck] [Info] >> VariableManager: 0 variables found
22:29:24 [Macro Deck] [Info] >> PluginManager: Loading plugins...
22:29:24 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
22:29:24 [Macro Deck] [Info] >> This action button version 2.12.0.221941808 enabled (took 1ms)
22:29:24 [Macro Deck] [Info] >> Macro Deck variables version 2.12.0.221941808 enabled (took 1ms)
22:29:24 [Macro Deck] [Info] >> Macro Deck folder version 2.12.0.221941808 enabled (took 0ms)
22:29:24 [Macro Deck] [Info] >> Device version 2.12.0.221941808 enabled (took 0ms)
22:29:24 [Macro Deck] [Info] >> PluginManager: Plugins enabled
22:29:24 [Macro Deck] [Info] >> IconManager: Loading icon packs...
22:29:24 [Macro Deck] [Info] >> IconManager: Loaded 0 icon packs
22:29:24 [Macro Deck] [Info] >> ProfileManager: Loading profiles...
22:29:24 [Macro Deck] [Info] >> Saved 1 profiles
22:29:24 [Macro Deck] [Info] >> Saved 1 profiles
22:29:24 [Macro Deck] [Info] >> Loaded 1 profiles
22:29:24 [Macro Deck] [Info] >> Starting websocket server @ 192.168.0.101:8191
22:29:24 [Macro Deck] [Info] >> Starting USB websocket server @ 127.0.0.1:8191
22:29:24 [Macro Deck] [Warning] >> ADBServerHelper: Cannot start adb server at C:\Users\juanj\AppData\Local\Temp\.net\Macro Deck 2\SXBJAH20YW6MeYtPR3JnNFjfmGmxWL0=\Android Debug Bridge\adb.exe: File not found
22:29:24 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
22:29:24 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server complete
22:29:25 [Macro Deck] [Info] >> Macro Deck startup finished (took 903ms)
22:29:59 [Macro Deck] [Info] >> ExtensionStoreDownloaderItem: Start installation of Spotify Plugin version 1.2.1
22:29:59 [Macro Deck] [Info] >> PluginManager: Installing Develeon64.SpotifyPlugin
22:30:00 [Macro Deck] [Info] >> Loading plugin SpotifyPlugin
22:30:30 [Macro Deck] [Info] >> ExtensionStoreDownloader: *** Installation of 1 package(s) done ***
22:30:49 [Macro Deck] [Info] >> ExtensionStoreDownloaderItem: Start installation of SoundPadPlugin version 0.2.9
22:30:49 [Macro Deck] [Info] >> PluginManager: Installing PhoenixWyllow.SoundPadPlugin
22:30:50 [Macro Deck] [Info] >> Loading plugin SoundPadPlugin
22:30:50 [Macro Deck] [Info] >> ExtensionStoreDownloader: *** Installation of 1 package(s) done ***
22:31:10 [Macro Deck] [Info] >> ExtensionStoreDownloaderItem: Start installation of OBS-WebSocket Plugin version 1.4.1
22:31:10 [Macro Deck] [Info] >> PluginManager: Installing SuchByte.OBS-WebSocketPlugin
22:31:11 [Macro Deck] [Info] >> Loading plugin OBS-WebSocket Plugin

**Comment by wirytiox** [comment]
i tried deletting the obs folder from appdata and it turned on. not sure why that happens but maybe there should be some kind of plug in tester when the program doesn't turn on...

**Comment by SuchByte** [comment]
The OBS Plugin had some issues. It should be fixed now.
