### ISSUE TITLE
Macro deck is not opening on PC

### ISSUE THREAD

**Issue by Adrian000000000** [Macro-Deck-App/Macro-Deck#399]
**Describe the bug**
Yesterday I was working on the macro deck for the first time and everything was alright, but after shutting down my computer and turning it on today the program is not opening even after reinstalation, can you please help me?

**Comment by SuchByte** [comment]
Please upload the latest log file. Logs are located in %Appdata%\Macro Deck\logs

**Comment by SuchByte** [comment]
The Ize.HWiNFO64 plugin could causing this problem. If you installed this plugin, try to uninstall the plugin manually. Open the Explorer and navigate to %AppData%\Macro Deck\plugins and delete the folder called Ize.HWiNFO64. After that, Macro Deck will start as normal.
