### ISSUE TITLE
Macro deck is not opening

### ISSUE THREAD

**Issue by Wojreq** [Macro-Deck-App/Macro-Deck#401]
I am trying to open macro deck but when i open it nothing happend i see anomaly in code but i dont know how it works

Log files:
10:19:16 [Macro Deck] [Info] >> Starting Macro Deck version 2.12.0 build 221941808
10:19:16 [Macro Deck] [Info] >> Executable: C:\Program Files\Macro Deck\Macro Deck 2.exe
10:19:16 [Macro Deck] [Info] >> OS: Windows 8 build 9200 64 bit
10:19:16 [Macro Deck] [Info] >> Network interfaces: 
Ethernet - 169.254.172.251
Połączenie lokalne* 1 - 2137.69.420
Połączenie lokalne* 12 - 2137.69.420
Wi-Fi - 192.168.50.191
Połączenie sieciowe Bluetooth - 169.254.236.216
Loopback Pseudo-Interface 1 - 127.0.0.1
10:19:16 [Macro Deck] [Info] >> Loading language files...
10:19:16 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
10:19:17 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
10:19:17 [Macro Deck] [Info] >> Successfully read configuration file
10:19:17 [Macro Deck] [Info] >> Set language to Polish
10:19:17 [Macro Deck] [Info] >> VariableManager: Initialize variables database...
10:19:17 [Macro Deck] [Info] >> VariableManager: 72 variables found
10:19:17 [Macro Deck] [Info] >> PluginManager: Loading plugins...
10:19:17 [Macro Deck] [Info] >> Loading plugin HWiNFO64
10:19:17 [Macro Deck] [Info] >> Loading plugin Speedtest
10:19:17 [Macro Deck] [Info] >> Loading plugin ShareX Plugin
10:19:17 [Macro Deck] [Info] >> Loading plugin SoundPadPlugin
10:19:17 [Macro Deck] [Info] >> Loading plugin Voicemeeter Plugin
10:19:17 [Macro Deck] [Info] >> Loading plugin Discord Plugin
10:19:17 [Macro Deck] [Info] >> Loading plugin OBS-WebSocket Plugin
10:19:17 [Macro Deck] [Info] >> Loading plugin Twitch Plugin
10:19:17 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
**10:19:17 [Macro Deck] [Error] >> MacroDeck: CurrentDomainOnUnhandledException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ize.HWiNFO64_Plugin.HWiNFO64Plugin.Enable() in C:\Users\Manuel\Desktop\Macro Deck Compiler\Temp\Ize.HWiNFO64\Main.cs:line 36
   at SuchByte.MacroDeck.Plugins.PluginManager.EnablePlugins() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\Plugins\PluginManager.cs:line 492
   at SuchByte.MacroDeck.MacroDeck.Start(Boolean show, Int32 port) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 447
   at SuchByte.MacroDeck.MacroDeck.Main(String[] args) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 415**

**Comment by SirHaxe** [comment]
delete the HWiNFO64 plugin and try again
