### ISSUE TITLE
cant connect to the host

### ISSUE THREAD

**Issue by anarthriagalumphed** [Macro-Deck-App/Macro-Deck#402]
I've been trying to use my older phone which is Android 5.1 but every time i tried to connect to the host this pop up showing

![image](https://github.com/Macro-Deck-App/Macro-Deck/assets/108788885/ee13bfac-433b-498d-9e59-89380ae1ce2a)

**Comment by SuchByte** [comment]
This is not a bug. Either you selected the wrong network interface, the port is blocked, your firewall blocks Macro Deck, you're using a vpn... 

https://github.com/Macro-Deck-App/Macro-Deck/wiki/Frequently-asked-questions
