### ISSUE TITLE
Macro deck refuses to open 

### ISSUE THREAD

**Issue by Caiioan** [Macro-Deck-App/Macro-Deck#403]
my log file is: 
[2023-05-30.log](https://github.com/Macro-Deck-App/Macro-Deck/files/11602938/2023-05-30.log)

**Comment by SuchByte** [comment]
The Ize.HWiNFO64 plugin could causing this problem. Try to uninstall the plugin manually. Open the Explorer and navigate to %AppData%\Macro Deck\plugins and delete the folder called Ize.HWiNFO64. After that, Macro Deck will start as normal.

**Comment by Caiioan** [comment]
worked Thanks
