### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by miki2coder** [Macro-Deck-App/Macro-Deck#405]
**Describe the bug**
Hi I add profile named "l"
after it i change 100 columns x 10000 rows and it crashed so i restart macro deck. (now I was trying to delete it)After the restart it was really laggi after I switched to "l" profile and it crashed. And over and over.

How can i delet the profile "l" without go into it?

**To Reproduce**

(If you do the program wont work forever and you will need to reinstal it )

1. create new profile
2. change row to 100000000

**Expected behavior**
I was expection to get max numer of rows

[2023-06-03.log](https://github.com/Macro-Deck-App/Macro-Deck/files/11643516/2023-06-03.log)

**Comment by SuchByte** [comment]
In that case you have two options:

- Open the database using a SQLite editor and remove the profile manually
- Delete the entire profiles database

The profiles database is located under `%Appdata%\Macro Deck` (profiles.db)
