### ISSUE TITLE
Doesn't connect anymore

### ISSUE THREAD

**Issue by GatoMorado621** [Macro-Deck-App/Macro-Deck#413]
I can't connect my tablet to the macro deck (pc) anymore. This is happening since 1 week or more. If anyone can help me I would really appreciate it a lot.

**Comment by manuelmayer-dev** [comment]
This is not a bug. This is always caused by a wrong configuration of your system.
https://github.com/Macro-Deck-App/Macro-Deck/wiki/Frequently-asked-questions
