### ISSUE TITLE
Cannot connect to the host.

### ISSUE THREAD

**Issue by RobynSNP** [Macro-Deck-App/Macro-Deck#414]
The application, which worked for a long time without any problems, started to give this error today. I'm sure I entered the IP and host address correctly, since the wifi is shared, it finds the device without typing. After clicking it says connect to device, after a long time can't connect to host. Then please make sure you type the correct ip address. It says bla bla. I tried to open and close the program on the computer, tried to delete and install it, tried the same on my android, tried turning the computer and android on and off, reset the modem, changed the dns address, nothing worked.

**Comment by RobynSNP** [comment]
By the way, I tried with a different phone, same error.

**Comment by KubeRl** [comment]
same here

**Comment by manuelmayer-dev** [comment]
This is not a bug. This is always caused by a wrong configuration of your system.
https://github.com/Macro-Deck-App/Macro-Deck/wiki/Frequently-asked-questions
