### ISSUE TITLE
Cannot open macro deck after installation

### ISSUE THREAD

**Issue by zhdingdang** [Macro-Deck-App/Macro-Deck#415]
My computer system is Windows 11 Professional Edition Insider Preview 22H2. Windows Feature Experience Pack Version: 1000.23440.1000.0. The first time I installed Macro Deck, it was unable to run normally after installation. There were no pop-up windows, and I couldn't find any logs.

**Comment by ABUCKY0** [comment]
I had this issue, I fixed it by installing it for all users instead of just myself.

**Comment by M4XM77R** [comment]
even after following this i cant get it to open

**Comment by FOXXTR** [comment]
i have the same problem. but it was a working 2 days ago and yesterday it wont open im try reinstall but its not working anymore 

win 10 pro 22H2 Windows Feature Experience Pack 1000.19041.1000.0

**Comment by manuelmayer-dev** [comment]
Try it with the latest beta version.

**Comment by YRS112** [comment]
The macro deck was working perfectly on W10. After installing the update, the software simply won't open!
