### ISSUE TITLE
My tablet is not conneting

### ISSUE THREAD

**Issue by Matteo10033** [Macro-Deck-App/Macro-Deck#419]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Log file**
Please upload the latest log file (Help -> Export latest log)

**Comment by manuelmayer-dev** [comment]
This is not a bug. This is a issue of your network/os configuration.
Here are some solutions: https://github.com/Macro-Deck-App/Macro-Deck/wiki/Frequently-asked-questions
