### ISSUE TITLE
i can not download plugins

### ISSUE THREAD

**Issue by HazemMahmoud0** [Macro-Deck-App/Macro-Deck#423]
![Screenshot (243)](https://github.com/Macro-Deck-App/Macro-Deck/assets/138934342/1c33ed2e-fedd-47e9-be23-0ef780dd990b)

[2023-07-07.log](https://github.com/Macro-Deck-App/Macro-Deck/files/11985816/2023-07-07.log)

**Comment by yoyogamerz0** [comment]
same thing وانت اصلا عربي

**Comment by manuelmayer-dev** [comment]
Fixed with https://github.com/Macro-Deck-App/Macro-Deck/pull/436
