### ISSUE TITLE
Will HTTPS be supported in the future?

### ISSUE THREAD

**Issue by cwbeta** [Macro-Deck-App/Macro-Deck#426]
I'm trying to make a local website at home, which contains the MacroDeck web and Home Assistant web and so on. So I can use several functions on one website and it's cool!

However, the web client of MacroDeck only supports HTTP and my website is over HTTPS to use remote access when I'm away from home.

Macro Deck is such a cool app. Thank you for your effort. I wonder if HTTPS will be supported in the future? Thank you!

**Comment by manuelmayer-dev** [comment]
It is planned for the future, yes.

**Comment by cwbeta** [comment]
It's great to hear that! Good job!
