### ISSUE TITLE
Change DB icon and obs source value

### ISSUE THREAD

**Issue by criquio** [Macro-Deck-App/Macro-Deck#429]
Hi there! I'm wondering if there is a way to change a MD button value and input that value to an obs text source so I could create a scoreboard directly into obs without the need of an external app once it's kinda hard to manage external sources value.

What's my idea: a way to increase/decrease a number in a MD button and input this number to an obs text source. I'd have 4 buttons for this: one to increase home team score, another one to decrease this score and the other two to do the same for visitor team score.

Change the button value is not mandatory. Change the obs source value is the point here.

I could overcoming this issue by adding multiple buttons with static numbers let's say 10 buttons for each team but it'd take a huge amount of buttons or maybe I could add a variable to a button that changes the text source target so I'd have one button to control the text source target and unique buttons for the numbers. It would still take unacessary extra buttons.

I've tried to find a way on myself with no success up till now.

If there is not this possibility yet, I strong suggest its adding 🤠
Cheers and congrats for your great work!

EDIT: I've just figured out how do it. I created an integer variable for count up/down and set it to change the obs source value to its own value.

**Comment by manuelmayer-dev** [comment]
Wrong repository
