### ISSUE TITLE
MD does not show grouped sources

### ISSUE THREAD

**Issue by criquio** [Macro-Deck-App/Macro-Deck#430]
Hi there! I'd like to let you know that there's a bug that does not let MD shows sources inside groups. Every time I have to edit a button whose action target is inside a group, I have to ungroup the sources, edit the action and then, regroup them. It's kinda annoying because sometimes I have actions to the group itself.

I am attaching some pictures to this post so you can understand it better:

![Macro Deck 01](https://github.com/Macro-Deck-App/Macro-Deck/assets/26008644/0be53428-b07e-44a7-b9ea-06e32e4fa1ab)
![Macro Deck 02](https://github.com/Macro-Deck-App/Macro-Deck/assets/26008644/e9f667bc-b27d-42ff-b830-b2ca20535a3b)

I'd also like to make a suggestion: I have 3 portable OBSs and MD "Bind state to" inside "Button state" group list brings all the scenes and sources from both the three even if I have only one of them opened and it even shows already deleted scenes and sources which makes it very extensive. It's hard to find a source in the list. It would be very appreciated if you manage to add a feature that cleans the list and reload it with only the scenes and sources from the current OBS instance and also add a search field to help us find it easily. Another suggestion is to sort the list alphabetically because its completely randomly sorted as the picture below shows:

![Macro Deck 03](https://github.com/Macro-Deck-App/Macro-Deck/assets/26008644/58644370-fbe0-4f51-972a-f606e39f7dbf)

I think that's all for now. Thanks!

**Comment by manuelmayer-dev** [comment]
Wrong repository
