### ISSUE TITLE
Button Background Color fills entire Button ony with color

### ISSUE THREAD

**Issue by manuelkamp** [Macro-Deck-App/Macro-Deck#470]
**Describe the bug**
I set up a if/then condition, where I set the background to red or nothing (=default bgcolor = green). If I now click the button on my android phone, the entire button fills with red (no icon anymore visible, no Colour gradient as it is shown in the windows app).

**To Reproduce**
klick the button on android.
see it filled completely with red and missing the icon.

**Expected behavior**
see the icon on the button with the red gradient like it is shown in the windows app.

**Screenshots**
![Screenshot_2023-11-25-13-53-54-93_2247855864d8390155bc19abbd60281e](https://github.com/Macro-Deck-App/Macro-Deck/assets/48356947/d8c9c322-df1c-4bad-abb8-f61cdc0ec814)
![Screenshot_2023-11-25-13-53-58-08_2247855864d8390155bc19abbd60281e](https://github.com/Macro-Deck-App/Macro-Deck/assets/48356947/7523c556-3224-4581-8f9a-a37c15d6a792)

**Comment by manuelmayer-dev** [comment]
This is expected behaviour. You have a separate icon for button state on/off. The gradient comes from the selected icon which is in the foreground. The color is in the background.
