### ISSUE TITLE
Keep awake not working

### ISSUE THREAD

**Issue by manuelkamp** [Macro-Deck-App/Macro-Deck#471]
**Describe the bug**
Keep awake is not working. It does not matter which setting I try (when connected, always). After the screen off time on my android device (Oneplus 9 Pro), the screen goes black and locks.

**Expected behavior**
screen does not shut off and locks, it should stay on always.

**Comment by manuelmayer-dev** [comment]
Wrong repository, this is the server. I'm currently working on a rewrite of the app.
