### ISSUE TITLE
Unable to connect to MacroDeck via web socket. Microsoft Edge

### ISSUE THREAD

**Issue by teateateateateatea** [Macro-Deck-App/Macro-Deck#475]
**Describe the bug**
Using MS Edge OR Chrome to run MacroDeck web page but fails to load page. 

web.macrodeck.org works fine. Connecting to the application doesn't work.

**To Reproduce**
1. Use MS Edge (Version 120.0.2210.61 (Official build) (64-bit))
2. Go to https://web.macrodeck.org/
3. Connect to your Macrodeck. In this case, it's my PC's local IP address
4. Always attempting to connect.
5. Right Click on Page on click on Inspect
6. Go to Console to note the following errors:

client.js:159  Mixed Content: The page at 'https://web.macrodeck.org/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://[Local IP Address]:8191/'. This request has been blocked; this endpoint must be available over WSS.

Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at connect (https://web.macrodeck.org/js/client.js:159:14)
    at HTMLFormElement.<anonymous> (https://web.macrodeck.org/js/client.js:87:3)
    at HTMLFormElement.dispatch (https://web.macrodeck.org/js/jquery-3.5.1.min.js:2:43090)
    at v.handle (https://web.macrodeck.org/js/jquery-3.5.1.min.js:2:41074)

**Expected behavior**
Opens up the web page Macrodeck

**Screenshots**
![TinyTake12-12-2023-02-09-30](https://github.com/Macro-Deck-App/Macro-Deck/assets/117501727/54ecf160-b404-4005-8d6a-c2cbb22203c0)

**Additional context**
This works as expected on Firefox.

**Comment by holiveira84** [comment]
Hello I have a similar problem in my case the wesit does not load at all browser Google Chrome

**Comment by manuelmayer-dev** [comment]
You need to access the web client without SSL (http://web.macrodeck.org)

If you're using the latest beta you can enable SSL support in the server and then access the server's ip address using HTTPS.
