### ISSUE TITLE
When having a lot of folders not possible to scroll to choose folder to go to with button press

### ISSUE THREAD

**Issue by Yerionimous2** [Macro-Deck-App/Macro-Deck#477]
**Describe the bug**
When you add a lot of folders the folders go off the screen when trying to set up a button to change to a folder and you are not able to choose any folder.

**To Reproduce**
1. create a lot of folders(for me: everything above 17)
2. create a new button
3. choose "macro deck folders"
4. choose "go to folder"
5. see error
I have set the App to german so the Options might have different names.

**Expected behavior**
I want to be able to scroll down there

**Screenshots**
![Unbenannt](https://github.com/Macro-Deck-App/Macro-Deck/assets/97311107/27ce8a69-583c-4d6e-b536-706943e4fe49)

Screenshot with (temporary) fix: i create new folder with different folders inside so i can collapse them. increases the number of folders available.

**Additional context**
If you need more context please ask, not sure what to put here.

**Log file**
Sadly i am not sure where to generate a log, but this is a UI problem, not really a problem where log can help i think.

**Comment by manuelmayer-dev** [comment]
Will be fixed in the next version
