### ISSUE TITLE
Add automatic reconnection functionality to the web client

### ISSUE THREAD

**Issue by mr-hash-888** [Macro-Deck-App/Macro-Deck#481]
I placed an old iPad next to my computer to serve as a display for the web client. The iPad has been jailbroken. After each computer startup, the iPad automatically unlocks the screen and displays the browser. However, the web client page requires manual reconnection every time. I noticed that the web client has already recorded the last connected IP address. Please modify it so that when the web client is opened, it attempts to automatically reconnect to the last IP address at specified intervals. This would be extremely helpful for me! Thank you for your work. 

I have designed a prototype for this feature as a reference.
![image](https://github.com/Macro-Deck-App/Macro-Deck/assets/57638013/940a22ae-ed2d-4b9c-87a6-007e096a3ab1)

**Comment by CrazyWolf13** [comment]
Full support on this, so annoying, cause the "Found Devices" just not works all the time, so manual interference is neccessary.

**Comment by jbcarreon123** [comment]
Already implemented on the new Macro Deck Client (that is built-in to MD 2.13.0).

**Comment by CrazyWolf13** [comment]
> Already implemented on the new Macro Deck Client (that is built-in to MD 2.13.0).

What about the android client?
