### ISSUE TITLE
When will it be compatible with Mac?

### ISSUE THREAD

**Issue by lcl-101** [Macro-Deck-App/Macro-Deck#484]

**Comment by cooltings** [comment]
please add mac support

**Comment by CrazyWolf13** [comment]
@lcl-101 @cooltings Please close this issue, this is already planned and set to be released with macrodeck 3
Announcement made in the Macrodeck Discord.

https://discord.gg/yQBmHFD8
https://discord.com/channels/869913729939148800/869915818480271410/1186436784704462978

**Comment by jbcarreon123** [comment]
## Planned for Macro Deck 3.
Also duplicate. See #376.
