### ISSUE TITLE
Twitch Plugin Variable USER_followers not available in selectbox

### ISSUE THREAD

**Issue by aschu875** [Macro-Deck-App/Macro-Deck#487]
**Describe the bug**
The USER followers variable cannot be selected in the variable selection box

**To Reproduce**
1. install twitch plugin
2. config twitch plugin
3. config button by doubleclick select (x) and try add variable USER_followers

**Comment by jbcarreon123** [comment]
# Wrong repository!
Go to the [Twitch Plugin issue tracker](https://github.com/manuelmayer-dev/Macro-Deck-Twitch-Plugin/issues) and post it there.
