### ISSUE TITLE
impossible to connect to obs and the plugin constantly asks to update (I use the beta version)

### ISSUE THREAD

**Issue by BenMitnicK** [Macro-Deck-App/Macro-Deck#489]
**Describe the bug**
impossible to connect to obs and the plugin constantly asks to update

**To Reproduce**
1. Download and install beta version
2. download and install websocket for OBS
3. Configure the plugin

**Screenshots**
OBS-Websocket error:

![macrodeck_1](https://github.com/Macro-Deck-App/Macro-Deck/assets/2843334/be2dc485-4f3a-49d2-a226-bc5e64355515)

Update loop

![macrodeck_2](https://github.com/Macro-Deck-App/Macro-Deck/assets/2843334/51ba8193-889e-463f-83c9-1c52af0a95d2)

![macrodeck_3](https://github.com/Macro-Deck-App/Macro-Deck/assets/2843334/663375ac-93a2-4a04-87c3-f3e2359192e7)

![macrodeck_4](https://github.com/Macro-Deck-App/Macro-Deck/assets/2843334/3243bbdf-a7d9-4af8-8181-25ca6fe27ee9)

**Additional context**
here is the error message => 10:21:47 PM [OBS-WebSocket Plugin] [Error] >> Error occurred while connecting to OBS instance. Error message: Invalid URI: The format of the URI could not be determined.

and for updating the plugin even though I install it for him there is always one

**Log file**
[Logs](https://pastebin.com/Z4rA9rzX)

**Comment by jbcarreon123** [comment]
# Wrong repository.
Go to the [OBS Plugin issue tracker](https://github.com/RecklessBoon/Macro-Deck-OBS-WebSocket-Plugin/issues) and post your issue there.
