### ISSUE TITLE
On release is triggered when mouse hover leaves button in web client

### ISSUE THREAD

**Issue by emerysteele** [Macro-Deck-App/Macro-Deck#505]
**Describe the bug**
Button "On release" action is triggered when mouse is hovered over the button, then leaves

**To Reproduce**
1. Create a button with an 'On release' action
2. Open web client
3. Hover over button with mouse
4. Move mouse off of button

**Expected behavior**
On release should only be triggered with click release, not with hover

**Screenshots**
![firefox_ErjqiKD0Wy](https://github.com/Macro-Deck-App/Macro-Deck/assets/1169001/6a4336f9-8133-4479-9415-109d19a0e269)

**Additional context**
Tested with Chrome, Firefox, and Edge. All same problem. v 2.13.1

**Log file**
[2024-03-17.log](https://github.com/Macro-Deck-App/Macro-Deck/files/14629962/2024-03-17.log)

**Comment by manuelmayer-dev** [comment]
Should be fixed with https://github.com/Macro-Deck-App/Macro-Deck/pull/520
