### ISSUE TITLE
Can't connect with Macro Deck client with SSL Enabled on server

### ISSUE THREAD

**Issue by patin-osu** [Macro-Deck-App/Macro-Deck#509]
**Describe the bug**
When SSL enabled, Macro Deck Client (Android Only, I'm not sure of iOS client) can't connect but Web Client can connect normally

**To Reproduce**
1. Make sure that SSL enabled in server
2. Go to Macro Deck Client
3. Try to connect to a server w/ SSL enabled

**Expected behavior**
It should connect normally

**Screenshots**
Macro Deck Server Settings:
![image](https://github.com/Macro-Deck-App/Macro-Deck/assets/75104667/b8a74d14-0d09-40fc-b747-2fa5dfad282e)
Macro Deck Client:
![Screenshot_2024-03-31-12-59-27-520_com suchbyte macrodeck](https://github.com/Macro-Deck-App/Macro-Deck/assets/75104667/be6304c1-de46-4632-b617-06d56f993637)

**Additional context**
¯\_(ツ)_/¯

**Log file**
[2024-03-31.log](https://paste.lol/patin/macrodeck-3-31-2567)

**Comment by manuelmayer-dev** [comment]
Currently only the integrated web client and the iOS app support SSL connections. The current Android app does not support SSL.
