### ISSUE TITLE
Disconnecting after a while - permanent connection possible?

### ISSUE THREAD

**Issue by hijacker2004** [Macro-Deck-App/Macro-Deck#514]
hello. i have the problem that when i use the macro deck on my android phone connected to my pc and OBS, the connection is disconnected after a while. how do i prevent this? is there a way to automatically reconnect or stay connected? or another solution?

**Comment by manuelmayer-dev** [comment]
This is not by design and should not happen. Make sure your connection is stable and your phone does not interrupt the connection. Maybe disabling battery optimization for the Macro Deck app could solve this problem.
