### ISSUE TITLE
Android Client App 3.0.0 Double Triggerint on "On Release"

### ISSUE THREAD

**Issue by nixonwong** [Macro-Deck-App/Macro-Deck#518]
**Describe the bug**
In Android client app 3.0.0, after triggering action(s) with "On release", the same action will be triggered by pressing other button(s). Tested with an older version (2.4.0, I think), and web client, neither of them have this bug.

**To Reproduce**
1. Set up the first button with "On release" as trigger; set action as "Macro Deck folder - Go to parent folder."
2. Set up the second button with "On press" as trigger. For the action, I have tested with Change folder, Discord Plugin toggle mute, and Windows Util's Hotkey.
3. Press and release the first button in the Android client 3.0.0. It should behave normally.
4. This step is where the unexpected behavior occurs. Press and release the second button (in the Android client 3.0.0.). About 7 out of 10 time, that will trigger the action of the second button, and also the first button.

**Expected behavior**
Pressing the second button should not trigger the action of the first button.

**Extra note**
1. The 3.0.0 android client had been tested on Android version 8.1.0, and Android 14, unexpected behavior were consistent.
2. Goto parent folder, and Windows Util's Hotkey have been tested as the action of the first button. Unexpected behavior consist.

**Comment by manuelmayer-dev** [comment]
Duplicate
https://github.com/Macro-Deck-App/Macro-Deck-Client-App/issues/11
