### ISSUE TITLE
Clients not connecting after May 2024 update (Win 10)

### ISSUE THREAD

**Issue by Theknight2015** [Macro-Deck-App/Macro-Deck#521]
So this may be something simple or it may be something I'm not doing correctly but I'm not sure. I came in to my home office this morning to the macro deck app not working on my tablet. It apparently updated because the interface is different. Instead of the "Automatic" search of the network and recent connections screen showing me my laptop running Macro deck, instead I was greeted with a page that shows a "Add connection" button. When I click on it, it takes me to a page where I can name the connection, enter the hostname/IP, the port and select whether or not to use SSL. I chose not to. Then I hit save and it took me back to the home screen of this newly updated Macro Deck app where it showed the connection but with a red WIFI symbol with a slash through it. I took this to mean it couldn't see the Macro Deck server running on my PC. I checked the laptop and updated Macro Deck on there from the package provided on the website. I also checked the firewall where there were several Macro Deck entries along with a couple Macro Deck 2 entries. All of them were set to Any protocol and any port except the Macro Deck 2 ones which one was set to UDP any Port and the other was set to TCP any port. I then checked the application on the PC/Server side and removed the existing connection to the old client because the new client ID was different than the old and I thought maybe the old client ID was messing with it since the old client ID and the new client ID were from the same IP address. Also just to note: The new client ID is not showing up in the PC/Server side application and I have tried both the ask for permission and always allow connections options.

I'm completely at a loss for what to try next. The only thing I get when trying to connect is a "Connecting to ws://192.xxx.xxx.xxx:8191..." as I try to connect to it but it times out after a couple minutes.

Any help would be appreciated.

I'm running the client on an older samsung tablet and the server side is on a win 10 machine.

**Comment by iprockbyte** [comment]
I also have problems, it no longer connects me, only from the same machine, I have returned to previous versions of the server, but it still doesn't work.

**Comment by manuelmayer-dev** [comment]
Since nothing network related changed in the server or in the client app, there must be something in your network which blocks the connection.

**Comment by iprockbyte** [comment]
Hi there!
I just tried to open an apache on port 8191 and from all clients it arrived perfectly, I don't understand it.

**Comment by Theknight2015** [comment]
> Since nothing network related changed in the server or in the client app, there must be something in your network which blocks the connection.

There's been nothing in the network that's changed and like I said, when the firewall is disabled on the server machine the client immediately fails to connect (when firewall is up it times out the connection after a couple minutes). That part makes no sense. no firewall and no block between the client and the sever means it should connect no problem but it doesn't.

**Comment by iprockbyte** [comment]
Now is working, it was the fucki** firewall, I do not why, I had to create
an exception suddenly.
Thank you very much for the support.
