### ISSUE TITLE
Changing a profile using an event

### ISSUE THREAD

**Issue by alinka62679** [Macro-Deck-App/Macro-Deck#526]
**Describe the bug**
The profile on the tablet does not automatically switch using an event (with a simple click on the button it works)

**To Reproduce**

![image](https://github.com/Macro-Deck-App/Macro-Deck/assets/72551624/0877ef46-6d8b-4bdc-8254-ffc6a7574580)

**Expected behavior**
Changing the profile on the tablet

**Video**
I switch between applications and the profile changes in the program on the computer, but not on the tablet

https://github.com/Macro-Deck-App/Macro-Deck/assets/72551624/dca03b66-7c19-4041-bca2-bcbdb4744d14

If I change profiles not through an event, but through pressing a button, then everything works

<details>
<summary>Button Settings</summary>

![image](https://github.com/Macro-Deck-App/Macro-Deck/assets/72551624/0a0f213f-57da-4cfd-8fbe-675630136eda)

</details>

https://github.com/Macro-Deck-App/Macro-Deck/assets/72551624/cae59ed6-a4a2-4f3f-b6cf-fcf9e56353a7

**Log file**
[2024-05-10.log](https://github.com/Macro-Deck-App/Macro-Deck/files/15279659/2024-05-10.log)

**Comment by alinka62679** [comment]
I realized that this can be done through folders, but the problem still remains

**Comment by manuelmayer-dev** [comment]
You need to change the target. Currently you set it to "Where executed" and because the event is executed on your computer, it changes the profile there. Change this to your tablet and it should work.
