### ISSUE TITLE
Buggy UI

### ISSUE THREAD

**Issue by CrazyWolf13** [Macro-Deck-App/Macro-Deck#530]
Hi 
The recent changes to Macrodeck are truly awesome!
Big thanks for maintaining and updating this <3

**Describe the bug**
Since a recent release, think it was 2.14.0 but could also be an earlier, my UI is extremely laggy and unresponsive.
For example, when I resize the window, it takes at long time to adjust and there are big visual black errors.

This happens for moving, resizing.

**To Reproduce**
1. Configure Macrodeck
2. Try moving the window
3. try resizing the window
4. See the visual errors

**Expected behavior**
I think that should not really happen. Altough the UI like this with a proper 
![image](https://github.com/Macro-Deck-App/Macro-Deck/assets/96661824/b7a2bcb9-779e-4f65-9560-e9916087f744)
Windows-ish title is already a HUGE step!
That also allows things like window managers to work, which is awesome!

**Log file**
Please upload the latest log file (Help -> Export latest log)
To be honest, not sure if the help sections has been moved or so, but I cannot find the export latest.log.

**Comment by Ramon20000** [comment]
Same issue here, also the button to open the cottle editor doesnt open and throws a error.
[2024-05-14.log](https://github.com/Macro-Deck-App/Macro-Deck/files/15311485/2024-05-14.log)

**Comment by CrazyWolf13** [comment]
@manuelmayer-dev  Thx for fixing ❤️
