### ISSUE TITLE
But that never fix

### ISSUE THREAD

**Issue by Progaming95967** [Macro-Deck-App/Macro-Deck#551]
I request to add open web site plugin with the URL like in stream deck but in a specific browser that we select please The website is too good and now I always use it But i always want to add this feature but I cant find and if it has a plugin that I say tell me the plugin name

-the reason I put this in bug report because you don't see it in feature 

-Thank you.

**Comment by Curros** [comment]
If you don´t find a plugin (I did not look) just use powershell, or some kind of script.

First look at google....
https://stackoverflow.com/questions/5776586/open-a-url-in-firefox-via-powershell

**Comment by Progaming95967** [comment]
Bro please add the feature I cant understand this
