### ISSUE TITLE
is macro deck a virus or does it have mem leaks?

### ISSUE THREAD

**Issue by officialkentech** [Macro-Deck-App/Macro-Deck#567]
started using 2gb+ mem

**Comment by officialkentech** [comment]
honestly i don't think it's a virus but it was suspicious af

**Comment by manuelmayer-dev** [comment]
tbh the code it quite old and not really good optimized. When using many icon packs and profiles, the memory usage can be higher because it's all loaded in memory. Macro Deck 3 will have this issues fixed.
